spring:
  profiles:
    active: default
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/lince_serverjava
    username: root
    password: 7_ap49y4z$n
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8090
  ssl:
    key-store: classpath:clever-bell.5-250-184-231.plesk.page_fullchain_and_key.p12
    key-store-password: 123456
    keyStoreType: PKCS12
logging:
    level:
        root: INFO
    file:
        name: /tmp/lince_serverJava.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB
reaktor:
  publicKeyFile: C:\claves\public_key.pem
  urlCors: http://localhost:5173, http://192.168.1.209:5173, http://192.168.1.181:5173, http://192.168.1.137:5173, http://172.20.10.2:5173