spring:
  jpa.hibernate.ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/lince_serverjava
    username: root
    password: qP8u-Ab80S_
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8090
  ssl:
    key-store: classpath:clever-bell.5-250-184-231.plesk.page_fullchain_and_key.p12
    key-store-password: 123456
    keyStoreType: PKCS12
logging:
    level:
        root: WARN
    file:
        name: /tmp/lince_serverJava.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB
