spring:
  jpa.hibernate.ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/lince_serverjava?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8090
logging:
    level:
        root: WARN
    file:
        name: /tmp/lince_serverJava.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB
reaktor:
  publicKeyFile: ${PUBLIC_KEY_FILE}
  urlCors: https://telemetrialince.iesjandula.es