spring:
  profiles:
    active: default
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/proyecto_lince
    username: root
    password: 7_ap49y4z$n
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8090
  ssl:
    key-store: classpath:clever-bell.5-250-184-231.plesk.page_fullchain_and_key.p12
    key-store-password: 123456
    keyStoreType: PKCS12
logging:
    level:
        root: TRACE
    file:
        name: /tmp/proyecto_lince.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB